import type { Article } from "../../types";

export const chatbotArticles: Article[] = [
  {
    id: "chatbot-configure-first-time",
    version: 1,
    title: "Como configurar o Chatbot IA",
    summary: "Ative o atendimento automático, escolha provedor, personalize mensagens e defina horários.",
    category: "ai",
    difficulty: "médio",
    minutes: 6,
    route: "/admin/chatbot",
    tourId: "chatbot-setup",
    steps: [
      {
        text: "Abra Chatbot IA. Esta tela controla o atendimento automático que responde mensagens recebidas no WhatsApp conectado.",
        image: { src: "/training/chatbot/settings.webp", alt: "Tela de configurações do Chatbot IA", pending: true },
      },
      { text: "Deixe o Chatbot IA desligado enquanto configura. Ligue somente depois de salvar, testar e conectar o WhatsApp do salão." },
      { text: "Escolha o provedor de IA e o modelo. Eles precisam combinar com a chave fornecida pelo provedor." },
      { text: "Cole a chave que o provedor forneceu no campo de chave. Ela fica guardada em sigilo; não envie essa chave por mensagem nem coloque em prints." },
      { text: "Ajuste o nome do bot e a mensagem para quando ele não consegue responder. O campo de boas-vindas é salvo, mas não é enviado automaticamente pelo atendimento no código atual." },
      { text: "Defina os dias e horários em que a IA pode responder. Fora do horário, o sistema usa a mensagem de fora do horário." },
      { text: "Clique em Salvar Configurações. O tour não salva nem liga o atendimento por você." },
    ],
    notes: [
      "O chatbot real é acionado pelo webhook do WhatsApp conectado e grava conversas em chatbot_conversations.",
      "A tela carrega configurações, base de conhecimento e histórico ao abrir, mas não grava no banco até salvar, adicionar ou excluir itens.",
      "O campo Boas-vindas é salvo, mas não é enviado automaticamente pelo atendimento atual. O rótulo Ativo reflete o ajuste na tela, não confirma a conexão do WhatsApp.",
    ],
    keywords: ["chatbot", "ia", "robô", "atendente", "configurar", "chave", "api key", "horário", "resposta automática"],
  },
  {
    id: "chatbot-train-knowledge",
    version: 1,
    title: "Como treinar o Chatbot com informações do salão",
    summary: "Edite o prompt e cadastre perguntas frequentes para respostas mais corretas.",
    category: "ai",
    difficulty: "médio",
    minutes: 5,
    route: "/admin/chatbot",
    tourId: "chatbot-knowledge",
    steps: [
      {
        text: "Abra a aba Treinamento. O prompt principal define o jeito de falar da IA e as regras gerais de atendimento.",
        image: { src: "/training/chatbot/training.webp", alt: "Aba Treinamento com prompt e base de conhecimento", pending: true },
      },
      { text: "Escreva orientações como: seja objetiva, não invente preços, peça dados do cliente quando for necessário e encaminhe casos difíceis para atendimento humano." },
      { text: "Use Instruções Personalizadas para informações do seu salão: endereço, políticas, serviços especiais, formas de pagamento e regras de atraso. Clique em Salvar Prompt quando quiser guardar as orientações; esse botão também salva os outros ajustes alterados na tela." },
      { text: "Na Base de Conhecimento, cadastre perguntas e respostas frequentes. Exemplos: preço do corte, endereço, horário, estacionamento e como remarcar." },
      { text: "Use palavras-chave separadas por vírgula para ajudar a encontrar o tema. Depois clique em Adicionar ao Conhecimento." },
      { text: "Revise a lista de conhecimentos com frequência. Remova respostas antigas e atualize qualquer informação que mudou." },
    ],
    notes: [
      "A função do chatbot também busca serviços cadastrados e itens da base de conhecimento para montar o contexto da resposta.",
      "Excluir um conhecimento remove o item do banco. O tour apenas explica a ação.",
    ],
    keywords: ["treinar", "conhecimento", "prompt", "perguntas", "respostas", "faq", "informações", "salão", "preços"],
  },
  {
    id: "chatbot-test-safely",
    version: 1,
    title: "Como testar o Chatbot com segurança",
    summary: "Use a aba Testar sabendo que a resposta atual é simulada.",
    category: "ai",
    difficulty: "fácil",
    minutes: 3,
    route: "/admin/chatbot",
    tourId: "chatbot-test",
    steps: [
      { text: "Abra a aba Testar e digite perguntas comuns de clientes, como preço, horário, endereço e como agendar." },
      { text: "A tela exige uma chave preenchida para liberar o campo de teste." },
      {
        text: "Leia o retorno com cuidado. No código atual, esta aba espera cerca de 1,5 segundo e mostra uma resposta simulada; ela não chama o provedor de IA real.",
        image: { src: "/training/chatbot/test.webp", alt: "Aba Testar com conversa simulada do chatbot", pending: true },
      },
      { text: "Use esta aba para revisar a experiência da tela, não para aprovar a qualidade final da IA." },
      { text: "Para teste real, salve as configurações, conecte o WhatsApp e envie uma mensagem controlada para o número do salão. Depois confira o Histórico." },
    ],
    notes: [
      "Confirmação no código: handleTestMessage, aproximadamente linhas 313-346, simula a resposta e não chama a IA real.",
    ],
    keywords: ["testar", "simulação", "teste", "mensagem", "resposta", "ia real", "provedor"],
  },
  {
    id: "chatbot-review-history",
    version: 1,
    title: "Como acompanhar o histórico do Chatbot",
    summary: "Veja mensagens processadas e use o histórico para melhorar o atendimento automático.",
    category: "ai",
    difficulty: "fácil",
    minutes: 3,
    route: "/admin/chatbot",
    tourId: "chatbot-history",
    steps: [
      { text: "Abra a aba Histórico. Ela mostra mensagens recebidas e respostas enviadas pelo chatbot." },
      { text: "Digite uma palavra da mensagem ou telefone na busca e clique no botão Atualizar ao lado. A pesquisa só é aplicada quando você atualiza a lista." },
      {
        text: "Confira a lista: mensagens do cliente e do assistente aparecem em ordem recente. Use Atualizar se estiver acompanhando conversas novas.",
        image: { src: "/training/chatbot/history.webp", alt: "Aba Histórico com mensagens do chatbot", pending: true },
      },
      { text: "Se encontrar respostas ruins, volte em Treinamento e corrija prompt, instruções ou base de conhecimento." },
      { text: "Nos primeiros dias com o chatbot ativo, confira o histórico diariamente." },
    ],
    notes: [
      "A lista traz até 100 mensagens mais recentes e não tem paginação nem filtro por data nesta tela.",
      "Mensagens recebidas podem ser registradas mesmo com o bot desligado. Mensagens da aba Testar ficam só na tela e não entram neste histórico.",
    ],
    keywords: ["histórico", "conversa", "mensagens", "cliente", "resposta", "erro", "acompanhar", "whatsapp"],
  },
];
