import type { Article } from "../../types";

export const settingsArticles: Article[] = [
  {
    id: "settings-complete-salon-info",
    version: 1,
    title: "Como preencher os dados do salão",
    summary: "Informe nome, contato e endereço para preparar o cadastro do estabelecimento.",
    category: "settings",
    difficulty: "fácil",
    minutes: 4,
    route: "/admin/settings",
    tourId: "settings-info",
    steps: [
      {
        text: "Abra Configurações do Salão. Se for seu primeiro cadastro, o título será Configurar Salão. O nome é obrigatório para salvar.",
        image: { src: "/training/settings/basic-info.webp", alt: "Informações básicas do salão com nome, endereço do link e descrição", pending: true },
      },
      { text: "Preencha Nome do Salão e confira Slug do Link Público. Este segundo campo define a parte do endereço após /s/; o sistema ajusta espaços e acentos para formar o link." },
      { text: "Escreva uma descrição curta para apresentar o salão na página pública. Preencha também Razão Social e CNPJ se quiser guardar esses dados." },
      { text: "Informe telefone, WhatsApp e e-mail de contato. Preencher WhatsApp aqui guarda o número do estabelecimento; não conecta o envio automático de mensagens." },
      {
        text: "Em Endereço, preencha rua, número, bairro, cidade, estado e CEP. Revise os dados para que o cliente saiba onde será atendido.",
        image: { src: "/training/settings/address.webp", alt: "Campos de endereço, cidade, estado e CEP do salão", pending: true },
      },
      { text: "Clique em Salvar no topo e aguarde a mensagem de confirmação. Esse botão cria o salão no primeiro cadastro e atualiza os dados nos seguintes. Depois, configure os horários de funcionamento." },
    ],
    notes: [
      "Alterar o endereço do link após divulgá-lo muda a página usada pelos clientes. Evite trocar sem atualizar os links que você compartilhou.",
      "O botão Salvar grava todos os campos alterados nesta tela, não apenas a seção que você acabou de preencher.",
    ],
    keywords: ["salão", "barbearia", "nome", "endereço", "telefone", "zap", "whatsapp", "e-mail", "contato", "cnpj", "slug", "cadastro"],
  },
  {
    id: "settings-configure-hours",
    version: 1,
    title: "Como definir os horários de funcionamento",
    summary: "Configure dias abertos, horários de atendimento e pausa para almoço.",
    category: "settings",
    difficulty: "fácil",
    minutes: 4,
    route: "/admin/settings",
    tourId: "settings-hours",
    steps: [
      {
        text: "Abra Configurações e encontre Horário de Funcionamento. Confira a linha de cada dia, de domingo a sábado.",
        image: { src: "/training/settings/weekly-hours.webp", alt: "Configuração semanal com dias abertos e horários de início e fim", pending: true },
      },
      { text: "Ative os dias em que o salão atende. Preencha início e fim nas linhas abertas; os dias desligados aparecem como Fechado." },
      { text: "Se a semana seguir o mesmo horário, configure a segunda-feira e use Copiar de Segunda para Todos. A cópia inclui a situação aberto ou fechado e atinge também sábado e domingo. Revise as exceções depois." },
      {
        text: "Se não houver atendimento durante o almoço, ative Pausa para Almoço. Defina início, fim e os dias em que essa pausa deve ser aplicada.",
        image: { src: "/training/settings/lunch-break.webp", alt: "Pausa para almoço com horário e seleção de dias", pending: true },
      },
      { text: "Revise os sete dias e clique em Salvar no topo. Depois, abra o link público para conferir a disponibilidade apresentada aos clientes, sem finalizar um agendamento apenas para experimentar." },
    ],
    notes: [
      "No salão novo, a lista semanal pode começar com todos os dias fechados. Configure e revise os dias antes de divulgar o agendamento.",
      "Copiar de Segunda para Todos só copia se a segunda-feira já tiver uma configuração. O botão não salva os dados no salão; use Salvar depois.",
    ],
    keywords: ["horário", "horários", "agenda", "dias", "semana", "domingo", "sábado", "aberto", "fechado", "almoço", "pausa", "funcionamento"],
  },
  {
    id: "settings-share-public-link",
    version: 1,
    title: "Como copiar e abrir o link de agendamento",
    summary: "Prepare o endereço público do salão para conferir a página e compartilhar com clientes.",
    category: "start",
    difficulty: "fácil",
    minutes: 3,
    route: "/admin/settings",
    tourId: "settings-public-link",
    steps: [
      { text: "Abra Configurações e preencha Slug do Link Público. Salve o salão: o cartão Link Público de Agendamento só aparece quando o salão está salvo e esse campo está preenchido." },
      {
        text: "No cartão do link, confira Agendamento Online Ativo. Se mudar a opção, clique em Salvar no topo para gravar a alteração.",
        image: { src: "/training/settings/public-link.webp", alt: "Cartão do link público com botões de copiar, abrir e opção de agendamento online", pending: false },
      },
      { text: "Clique em Copiar link, o botão com símbolo de cópia. Aguarde Link copiado e cole o endereço na conversa com o cliente ou no perfil do salão. O sistema copia o endereço, mas não envia uma mensagem." },
      { text: "Para conferir como o cliente vê o salão, clique em Abrir em nova aba. Se a aba não abrir, confira o bloqueio de novas janelas do navegador." },
      { text: "Confira dados do salão, serviços e profissionais antes de compartilhar. Abrir a página não cria um agendamento; só finalize um atendimento se realmente quiser cadastrá-lo." },
    ],
    notes: [
      "O endereço é formado pelo site que você está usando, seguido de /s/ e do nome definido no campo do link. Não divulgue endereços de demonstração como se fossem produção.",
      "Copiar ou abrir com sucesso registra esse passo no checklist. Isso não comprova que o link foi enviado a um cliente nem que ele recebeu a mensagem.",
      "Desativar o agendamento online bloqueia a página pública após salvar. O botão Copiar link ainda pode aparecer, por isso confira a opção antes de divulgar.",
    ],
    keywords: ["link", "agendamento", "online", "página", "público", "copiar", "abrir", "compartilhar", "whatsapp", "zap", "instagram", "endereço", "slug"],
  },
  {
    id: "settings-personalize-salon",
    version: 1,
    title: "Como escolher a cor e o logo do salão",
    summary: "Use Personalização para ajustar a cor principal e a imagem do estabelecimento.",
    category: "settings",
    difficulty: "fácil",
    minutes: 4,
    route: "/admin/settings",
    tourId: "settings-branding",
    steps: [
      {
        text: "Abra Configurações e encontre Personalização. Escolha a Cor Principal pelo quadrado colorido ou pelo código da cor ao lado.",
        image: { src: "/training/settings/branding.webp", alt: "Personalização com cor principal e opções de imagem do logo", pending: true },
      },
      { text: "Para usar uma imagem que já está na internet, abra Link URL e informe o endereço completo da imagem. Quando ela carrega, uma prévia aparece abaixo." },
      { text: "Para escolher um arquivo, salve o salão primeiro e abra Upload. Selecione uma imagem de até 2 MB. A escolha já envia o arquivo, mas ainda falta salvar o endereço do logo no cadastro do salão." },
      { text: "A aba Câmera permite abrir a câmera com sua autorização. Capturar envia a foto; Cancelar fecha a câmera. Use apenas quando realmente quiser tirar e enviar uma imagem." },
      { text: "Clique em Salvar para gravar cor e endereço do logo no salão. Depois abra o link público e confira a apresentação." },
    ],
    notes: [
      "Upload e captura dependem de o salão já estar salvo. Enviar a imagem ocorre antes do botão Salvar; sair sem salvar pode deixar um arquivo enviado sem atualizar o logo do salão.",
      "A câmera depende da permissão e do suporte do navegador. O tour não liga a câmera nem escolhe arquivos automaticamente.",
    ],
    keywords: ["logo", "logotipo", "imagem", "foto", "cor", "aparência", "personalização", "upload", "câmera"],
  },
  {
    id: "settings-browser-notifications",
    version: 1,
    title: "Como ativar notificações no navegador",
    summary: "Confira o suporte e a permissão para receber alertas no navegador usado pelo salão.",
    category: "settings",
    difficulty: "fácil",
    minutes: 2,
    route: "/admin/settings",
    tourId: "settings-notifications",
    steps: [
      {
        text: "Abra Configurações e vá até Notificações Push. Confira se o navegador mostra Ativadas, Desativadas, Notificações bloqueadas ou uma mensagem de falta de suporte.",
        image: { src: "/training/settings/browser-notifications.webp", alt: "Seção de notificações com situação e botão de ativação", pending: true },
      },
      { text: "Se quiser receber alertas, clique em Ativar e autorize o navegador quando ele pedir. Se estiverem bloqueadas, libere a permissão nas configurações do próprio navegador." },
      { text: "Para parar os alertas neste navegador, use Desativar. Essas ações alteram a inscrição de notificações imediatamente, sem clicar em Salvar do salão." },
      { text: "Quando disponível, Enviar notificação de teste nesta seção mostra um aviso na tela. Confira também os avisos recebidos no Dashboard; esse botão não comprova a entrega de uma notificação externa." },
    ],
    notes: [
      "A disponibilidade depende do navegador, da permissão e da configuração do serviço de notificações. Ativar aqui não conecta o WhatsApp.",
      "O botão Enviar notificação de teste deste componente apenas mostra um aviso na tela; não envia uma notificação externa de teste.",
    ],
    keywords: ["notificação", "notificações", "alerta", "aviso", "push", "navegador", "permissão", "bloqueado", "ativar", "desativar"],
  },
  {
    id: "settings-pix-information",
    version: 1,
    title: "Como entender o campo de PIX do salão",
    summary: "Conheça onde os dados de PIX são cadastrados e o que esse campo não faz.",
    category: "settings",
    difficulty: "fácil",
    minutes: 2,
    route: "/admin/settings",
    tourId: "settings-pix",
    steps: [
      { text: "Em Configurações, Informações Básicas inclui o campo Chave PIX. Ele guarda a informação de pagamento do salão para o fluxo de confirmação de agendamento." },
      { text: "Só preencha e confira dados de pagamento reais quando estiver configurando seu salão. Não use chaves reais em demonstrações, capturas ou materiais de treinamento." },
      { text: "Se alterar esse campo, clique em Salvar para gravar. Cadastrar a chave não efetua uma cobrança nem confirma o recebimento do pagamento." },
      { text: "Na confirmação do agendamento público, a área de PIX depende de haver uma chave cadastrada e um valor final maior que zero. Confira o pagamento pelo seu procedimento habitual." },
    ],
    notes: [
      "Esta configuração guarda um dado de PIX, não conecta uma cobrança automática nem confirma pagamento. Nenhuma chave real deve aparecer nas imagens de treinamento.",
    ],
    keywords: ["pix", "pagamento", "chave", "cobrança", "confirmar", "recebimento"],
  },
];
